import { addIcons } from 'ionicons';
import {
  searchOutline,
  locationOutline,
  timeOutline,
  hammerOutline,
  cubeOutline,
  appsOutline,
  cutOutline,
  leafOutline,
  colorPaletteOutline,
  gridOutline,
  storefrontOutline,
  mapOutline,
  arrowBackOutline,
  optionsOutline,
  chevronForwardOutline,
  refreshOutline,
  heart,
  heartOutline,
  callOutline,
  logoWhatsapp,
  navigateOutline,
  location,
  businessOutline,
  constructOutline,
  exitOutline,
  flashOutline,
  waterOutline,
  snowOutline,
  homeOutline,
  shieldCheckmarkOutline,
  buildOutline,
  settingsOutline,
  shieldOutline,
  flowerOutline,
  archiveOutline,
} from 'ionicons/icons';

export const registerGlobalIcons = () => {
  addIcons({
    'search-outline': searchOutline,
    'location-outline': locationOutline,
    'time-outline': timeOutline,
    'hammer-outline': hammerOutline,
    'cube-outline': cubeOutline,
    'apps-outline': appsOutline,
    'cut-outline': cutOutline,
    'leaf-outline': leafOutline,
    'color-palette-outline': colorPaletteOutline,
    'grid-outline': gridOutline,
    'storefront-outline': storefrontOutline,
    'map-outline': mapOutline,
    'arrow-back-outline': arrowBackOutline,
    'options-outline': optionsOutline,
    'chevron-forward-outline': chevronForwardOutline,
    'refresh-outline': refreshOutline,
    'heart': heart,
    'heart-outline': heartOutline,
    'call-outline': callOutline,
    'logo-whatsapp': logoWhatsapp,
    'navigate-outline': navigateOutline,
    'location': location,
    'business-outline': businessOutline,
    'construct-outline': constructOutline,
    'exit-outline': exitOutline,
    'flash-outline': flashOutline,
    'water-outline': waterOutline,
    'snow-outline': snowOutline,
    'home-outline': homeOutline,
    'shield-checkmark-outline': shieldCheckmarkOutline,
    'build-outline': buildOutline,
    'settings-outline': settingsOutline,
    'shield-outline': shieldOutline,
    'flower-outline': flowerOutline,
    'archive-outline': archiveOutline,
  });
};
